package com.italia.ipos.enm;

/**
 * 
 * @author mark italia
 * @since 02/13/2017
 * @version 1.0
 *
 */
public enum Features {

	GROCERRY_CASHIER("GROCERRY"),
	DELIEVRY("DELIVERY"),
	ACCOUNTING("ACCOUNTING"),
	INVENTORY("INVENTORY"),
	PRODUCT_GRAPH_LINE("GRAPH LINE"),
	PRODUCT_GRAPH_PIE("GRAPH PIE"),
	XTRAS("XTRAS"),
	STORE_TRANSFER("STORE TRANSFER"),
	ADMIN_USER("ADMIN USER"),
	ADMIN_CLIENT("ADMIN CLIENT"),
	ADMIN_SUPPLIER("ADMIN SUPPLIER"),
	ADMIN_PRODUCT("ADMIN PRODUCT"),
	CLIENTS("CLIENTS"),
	SUPPLIERS("SUPPLIERS"),
	STATISTICS("PRODUCT STATISTICS"),
	XTRA_PRODUCT_BUTTON("XTRA PRODUCT"),
	ON_HOLD_BUTTON("ON HOLD"),
	HISTORY_BUTTON("RECALL HISTORY"),
	ACCOUNTING_INCOMES("ACC INCOMES"),
	ACCOUNTING_EXPENSES("ACC EXPENSES"),
	ACCOUNTING_RECEIVABLE("ACC RECEIVABLE"),
	ACCOUNTING_PAYABLE("ACC PAYABLE"),
	ACCOUNTING_SUMMARY("ACC SUMMARY"),
	ACCOUNTING_SOLD_ITEMS("ACC SOLD"),
	CLIENT_RENTED_ITEMS("CLIENT RENTED"),
	CLIENT_COLLECTIBLE("CLIENT COLLECTIBLE"),
	DELIVERY_TRUCK("DELIVERY TRUCK"),
	DELIVERY_TRANSACTION("DELIVERY TRANSACTION"),
	DELIVERY_SOLD("DELIVERY SOLD"),
	DELIVERY_RETURN("DELIVERY RETURN"),
	DELIVERY_RENTED_ITEMS("DELIVERY RENTED"),
	CASHIER_PRODUCT_RETURN("PRODUCT RETURN"),
	
	ROOM_MONITORING("ROOM MONITORING"),
	TABLE_MONITORING("TABLE MONITORING"),
	PRODUCT_EXPIRATION_MONITORING("PRODUCT EXPIRATION MONITORING"),
	
	BASIC_FEATURES("BASIC"),
	CUSTOMIZE_FEATURES("CUSTOM"),
	
	AUTO_HOLD("AUTO HOLD"),
	CASHIER_CUSTOMER("CASHIER CUSTOMER"),
	VAT("VAT"),
	POINTS("POINTS");
	
	
	private String name;
	
	public String getName(){
		return name;
	}
	
	private Features(String name){
		this.name = name;
	}
	
}
